doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                url: '%env(resolve:DATABASE_URL)%'
                use_savepoints: true
            leads:
                url: '%env(resolve:VOYANCE_DATABASE_URL)%'
                use_savepoints: true

    orm:
        default_entity_manager: default
        entity_managers:
            default:
                connection: default
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
                auto_mapping: true
                mappings:
                    App:
                        is_bundle: false
                        dir: '%kernel.project_dir%/src/Entity'
                        prefix: 'App\Entity'
                        alias: App

            leads:
                connection: leads
                mappings:
                    Leads:
                        is_bundle: false
                        dir: '%kernel.project_dir%/src/Entity/Leads'
                        prefix: 'App\Entity\Leads'
                        alias: Leads
